name: Upload SHETRAN prepare to DAFNI

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -t pyramid-shetran-prepare:latest -f Dockerfile-prepare

      - name: Compress docker image
        run: docker save pyramid-shetran-prepare:latest | gzip > pyramid-shetran-prepare.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './pyramid-shetran-prepare.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "eb77ac58-c528-437c-ab45-5ba6d464d45b"
