name: Upload SHETRAN run to DAFNI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Upload SHETRAN run to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -t pyramid-shetran-run:latest -f Dockerfile-run

      - name: Compress docker image
        run: docker save pyramid-shetran-run:latest | gzip > pyramid-shetran-run.tar.gz
  
      - name: Copy correct model-definition.yml file for DAFNI uploader
        run: cp model-definition-run.yml model-definition.yml
  
      - name: Set tag as env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Verify release version tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './pyramid-shetran-run.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.RELEASE_VERSION }}
          parent-model: "6756ebb2-b1f6-41cf-87e1-58533583801d"
